######################################################################
# Automatically generated by qmake (2.01a) ? 11? 23 02:45:08 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += JolUpMain.h LectureAdd.h LectureModify.h MyInfo.h MyInfoData.h
FORMS += JolUpMain.ui LectureAdd.ui LectureModify.ui MyInfo.ui
SOURCES += JolUpMain.cpp LectureAdd.cpp LectureModify.cpp main.cpp MyInfo.cpp
